* HEGP Challenge

/Homomorphic Encryption of Genotypes and Phenotypes (HEGP)/

Here we announce the HEGP Challenge, with a prize for the person or
group who can crack the code!

** Sharing genotype data!

With a [[https://www.genetics.org/content/215/2/359][publication in Genetics]] we present a novel homomorphic
encryption method named HEGP that allows for sharing of genotypes and
phenotypes in the context of Genome Wide Association (GWA)
studies. Importantly sharing but without giving away *private*
information and making individuals identifiable.

With HEGP anyone can freely hand over genotype and phenotype data to
anyone else and have them reproduce the results.

Even better, they can use that data to add to their own analysis. And
they can share their data with us! As such, genotype data can be
stored on (public) servers and GWA analysis can be reproduced.

This is a breakthrough in [[https://en.wikipedia.org/wiki/FAIR_data][FAIR data]] sharing and contrasts greatly with
current practices of hiding/protecting genotype data and only
providing summary statistics (which are not reproducible).



** Is this encryption safe?

We tried find ways of cracking the code as discussed in our [[https://www.genetics.org/content/215/2/359][paper]].
Brute force guessing of a solution would take more compute seconds
than there are molecules in the universe.

** What is the challenge?

The challenge consists of decrypting two data sets.

For the first challenge we encrypted a data set consisting of data from
genotypes already in the public domain. We consider the code cracked
if you can identify 5 individuals correctly.

The second challenge is harder. We encrypted an unknown data set. We
consider the code cracked if you compute 30% of the genotypes of this
matrix correctly (we specify the margin of error).

* Who wins?

The best result with a publicly reproducible solution submitted by
October 1st 2020 wins the HEGP Challenge and a cash prize of one
thousand dollars. In case of a tie the prize is shared. If there is no
winner we will hold the prize until someone claims it.
